"""Self-contained interactive HTML reports.

Three pages, all single files with the CSS and JavaScript inlined: no CDN, no
build step, no network, so they open straight from the file system.

===================  ==========================================================
``index.html``        what the method is, and the two headline measurements
``branches.html``     every configuration that reaches one pose, drawn on top of
                      each other, with the elbow quadratic that produces them
``coverage.html``     does the solver find the configuration the pose came from?
===================  ==========================================================

All the geometry and arithmetic happens in Python; the page embeds the computed
arrays and inlines ``franka_ik/web/demo.js``, which only draws them.  Nothing is
recomputed in the browser, so what a reader sees is what the tests assert.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np

from . import model
from .analysis import (
    CoverageReport,
    SolutionCountReport,
    coverage_study,
    solution_count_study,
)
from .geometry import (
    PAPER_GEOMETRY,
    EquivalentGeometry,
    q4_coefficients,
    q4_discriminant,
    q4_roots,
    shoulder_to_wrist,
    wrist_correction,
)
from .solver import IkSolution, solve
from .viz import BRANCH_COLORS

__all__ = [
    "build_demo_site",
    "build_index_page",
    "build_branches_page",
    "build_coverage_page",
]

_ASSET_DIR = Path(__file__).resolve().parent / "web"

#: Pages of the generated site, as ``(file name, navigation label)``.
PAGES: Tuple[Tuple[str, str], ...] = (
    ("index.html", "overview"),
    ("branches.html", "solution branches"),
    ("coverage.html", "coverage study"),
)


def _read_asset(name: str) -> str:
    """Read a file from ``franka_ik/web``."""
    path = _ASSET_DIR / name
    if not path.is_file():
        raise FileNotFoundError(
            f"missing web asset {path}; reinstall so that franka_ik/web ships as package data"
        )
    return path.read_text(encoding="utf-8")


def _nav(current: str) -> str:
    """Navigation bar, with the current page marked."""
    links = []
    for file_name, label in PAGES:
        css = ' class="current"' if file_name == current else ""
        links.append(f'<a href="{file_name}"{css}>{label}</a>')
    return '<nav class="pages">' + "".join(links) + "</nav>"


def _page(file_name: str, title: str, subtitle: str, data: Dict) -> str:
    """Assemble a complete standalone HTML page."""
    payload = json.dumps(data, allow_nan=False, separators=(",", ":"))
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
{_read_asset("demo.css")}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>{subtitle}</p>
  {_nav(file_name)}
</header>
<main>
  <div class="grid">
    <section class="card">
      <h2>arm configurations</h2>
      <canvas id="scene" class="scene"></canvas>
      <div id="motion" class="motion"></div>
      <p id="motion-readout" class="motion-readout"></p>
      <div id="branches" class="branches"></div>
    </section>
    <section class="card">
      <h2>analysis</h2>
      <canvas id="chart" class="chart tall"></canvas>
      <div id="legend" class="legend"></div>
    </section>
  </div>
  <section class="card" id="table-card" style="margin-top:1.1rem">
    <h2>numbers</h2>
    <div id="table"></div>
  </section>
  <section class="card" style="margin-top:1.1rem">
    <h2>notes</h2>
    <div id="notes"></div>
  </section>
</main>
<footer>
  Generated by <code>franka_ik.report</code>.  The method is the one derived in
  <code>franka&#35299;&#26512;&#21453;&#35299;&#26041;&#27861;.pdf</code>: reduce the Panda to an equivalent S-R-S arm and solve
  that arm in closed form.  Every value on this page is computed in Python; the
  page only draws it.
</footer>
<script>
window.FRANKA_IK_DATA = {payload};
</script>
<script>
{_read_asset("demo.js")}
</script>
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# data assembly
# --------------------------------------------------------------------------- #
def _chain(q: Sequence[float]) -> List[List[float]]:
    """Joint origins of a configuration plus the flange, rounded for embedding."""
    frames = model.forward_kinematics(q)
    points = [[0.0, 0.0, 0.0]]
    points.extend(
        [float(value) for value in frames[index][:3, 3]] for index in range(model.NUM_JOINTS)
    )
    points.append([float(value) for value in frames[model.FLANGE_ROW][:3, 3]])
    return [[round(value, 6) for value in point] for point in points]


def _arm_dict(solution: IkSolution, index: int, target: Optional[Sequence[float]]) -> Dict:
    """One arm entry of the 3D scene."""
    recovers = False
    if target is not None:
        delta = solution.q - np.asarray(target, dtype=float)
        recovers = bool(np.all(np.abs(np.arctan2(np.sin(delta), np.cos(delta))) < 1e-6))
    return {
        "label": solution.label,
        "color": BRANCH_COLORS[index % len(BRANCH_COLORS)],
        "points": _chain(solution.q),
        "qDeg": [round(math.degrees(value), 4) for value in solution.q],
        "poseError": float(solution.pose_error),
        "withinLimits": bool(solution.within_limits),
        "recoversTarget": recovers,
    }


def _quadratic_panel(
    distance: float, geometry: EquivalentGeometry, samples: int = 401
) -> Dict:
    """Panel data for the STEP2 elbow quadratic, with both roots marked."""
    a2, a1, a0 = q4_coefficients(distance**2, geometry)
    roots = q4_roots(distance**2, geometry)
    scale = max(abs(a2), abs(a1), abs(a0), 1e-9)

    limit = 6.0
    xs = np.linspace(-limit, limit, samples)
    values = (a2 * xs**2 - a1 * xs + a0) / scale

    markers = []
    off_scale = []
    for index, theta4 in enumerate(roots):
        abscissa = math.tan(theta4 / 2.0)
        label = f"theta4 = {math.degrees(theta4):.2f} deg"
        if abs(abscissa) > limit:
            # theta4 approaching +-180 deg sends x = tan(theta4/2) to infinity;
            # the marker is pinned to the edge and the value is named instead.
            abscissa = math.copysign(limit, abscissa)
            label += " (off scale)"
            off_scale.append(math.degrees(theta4))
        markers.append(
            {
                "x": float(abscissa),
                "label": label,
                "color": ["#cb181d", "#238b45"][index % 2],
            }
        )
    title = (
        f"elbow quadratic at |x_sw| = {distance:.4f} m   "
        f"(discriminant {q4_discriminant(distance**2, geometry):+.4e})"
    )
    if off_scale:
        title += (
            "   --  root near theta4 = "
            + ", ".join(f"{value:.2f}" for value in off_scale)
            + " deg lies beyond the drawn range of tan(theta4/2)"
        )
    return {
        "title": title,
        "yLabel": "normalised",
        "xLabel": "x = tan(theta4 / 2)",
        "xValues": [round(float(value), 5) for value in xs],
        "series": [
            {
                "label": "a2 x^2 - a1 x + a0",
                "values": [round(float(value), 8) for value in values],
                "color": "#08519c",
                "width": 2.0,
            }
        ],
        "markers": markers,
    }


# --------------------------------------------------------------------------- #
# pages
# --------------------------------------------------------------------------- #
#: Colours for the two elbow roots on the branches page's sweep: two shades each, so
#: the four configurations of one root are still distinguishable from one another.
_ROOT_COLORS = {
    "plus": ("#08519c", "#6baed6"),
    "minus": ("#e6550d", "#fd8d3c"),
}


def _branch_track(
    pose: np.ndarray,
    q7: float,
    target: Optional[Sequence[float]],
    geometry: EquivalentGeometry,
    *,
    frames: int = 61,
    half_width_deg: float = 60.0,
    within_limits_only: bool = True,
) -> Dict:
    """A joint-7 sweep for the branches page's scrubber.

    The browser cannot solve the closed form, so the sweep is pre-computed here and
    embedded: every frame carries the configurations that reach the pose at one
    joint-7 value, and the slider simply selects a frame.  This is the same thing the
    sibling S-R-S study's HTML demos do, and it is what makes the page *move*.

    Frames with no in-limit solution are dropped rather than embedded as empty, and
    the joint-7 range is narrowed to the part that has any, so the slider never sits
    on a blank pose.

    Args:
        pose: 4x4 homogeneous flange pose.
        q7: The page's own joint 7, always included in the sweep.
        target: The configuration the pose came from, for the ``TARGET`` flag.
        geometry: Geometric parameters.
        frames: Joint-7 values to try; the ones without a solution are dropped.
        half_width_deg: Half-width of the sweep around ``q7``, in degrees.
        within_limits_only: Keep only in-limit configurations.

    Returns:
        ``{"q7Deg": [...], "parts": [[arm, ...], ...], "index": i}`` where ``index``
        selects the frame closest to ``q7``.
    """
    span = np.radians(half_width_deg)
    values = np.linspace(q7 - span, q7 + span, frames)
    parts: List[List[Dict]] = []
    kept: List[float] = []
    for value in values:
        found = solve(pose, float(value), geometry=geometry, within_limits_only=within_limits_only)
        if not found:
            continue
        kept.append(float(math.degrees(value)))
        frame_arms = [_arm_dict(solution, index, target) for index, solution in enumerate(found)]
        # Colour by *elbow root*, not by position in the list.  The list order shifts
        # as joint 7 moves, so index colours make an arm change colour mid-sweep; and
        # the roots are the thing this page is about -- blue is the half the published
        # code keeps, orange the half it drops.
        for arm in frame_arms:
            shade = 0 if "phi+" in arm["label"] else 1
            arm["color"] = _ROOT_COLORS["plus" if arm["label"].startswith("q4+") else "minus"][shade]
        parts.append(frame_arms)
    if not kept:  # pragma: no cover - a pose with no solution has no track to show
        return {"q7Deg": [], "parts": [], "index": 0}
    closest = min(range(len(kept)), key=lambda index: abs(kept[index] - math.degrees(q7)))
    return {"q7Deg": kept, "parts": parts, "index": closest}


def build_branches_page(
    pose: np.ndarray,
    q7: float,
    target: Optional[Sequence[float]] = None,
    geometry: EquivalentGeometry = PAPER_GEOMETRY,
) -> str:
    """Page 2: every configuration that reaches one pose.

    Args:
        pose: 4x4 homogeneous flange pose.
        q7: Joint 7 value in radians.
        target: The configuration the pose came from, highlighted when known.
        geometry: Geometric parameters.

    Returns:
        The HTML document.
    """
    solutions = solve(pose, q7, geometry=geometry, within_limits_only=True)
    arms = [_arm_dict(solution, index, target) for index, solution in enumerate(solutions)]

    rotation = np.asarray(pose, dtype=float)[:3, :3]
    position = np.asarray(pose, dtype=float)[:3, 3]
    corrected = rotation @ wrist_correction(q7, geometry)
    p_sw = shoulder_to_wrist(position, corrected, geometry)
    distance = float(np.linalg.norm(p_sw))

    rows = []
    for arm in arms:
        angles = ", ".join(f"{value:.2f}" for value in arm["qDeg"])
        marks = []
        if not arm["withinLimits"]:
            marks.append("out of limits")
        if arm["recoversTarget"]:
            marks.append("TARGET")
        rows.append(
            [
                arm["label"],
                angles,
                f"{arm['poseError']:.2e}",
                ", ".join(marks) if marks else "-",
            ]
        )

    data = {
        "kind": "branches",
        "arms": arms,
        "target": (
            None
            if target is None
            else {"points": _chain(target), "qDeg": [round(math.degrees(v), 4) for v in target]}
        ),
        "tool": [round(float(value), 6) for value in position],
        # The scrubber's frames.  Only the 3D scene and the readout follow it -- the
        # table and the quadratic panel describe the page's own joint 7.
        "motion": _branch_track(pose, q7, target, geometry),
        "toggleArms": True,
        "panels": [_quadratic_panel(distance, geometry)],
        "table": {
            "headers": ["branch", "joint angles (deg)", "pose error (m)", "flags"],
            "rows": rows,
        },
        "notes": [
            f"<b>{len(solutions)} distinct configurations</b> reach this flange pose with "
            f"joint 7 at {math.degrees(q7):.3f} deg, and every one of them is exact: the pose "
            "residual at the bottom of the table is the largest entry of "
            "<code>fk_flange(q) - target</code>, and it is at machine precision.",
            "The dashed black arm is the configuration the pose was generated from. "
            "Only a solver that enumerates <i>all</i> branches finds it; a solver with "
            "four branches returns four perfectly valid poses and misses it silently "
            "in roughly one case out of eight.",
            "The curve is the elbow quadratic of STEP2 of the derivation, drawn against "
            "<code>x = tan(theta4/2)</code>. Its <b>two</b> roots are marked. The published "
            "implementation kept only the positive one, which is exactly why it saw four "
            "The scrubber sweeps joint 7 across the values that reach this pose, and the "
            "3D view follows: <b>blue</b> arms are on the '+' elbow root, the half the "
            "published code keeps, and <b>orange</b> ones are on the '-' root it never "
            "evaluates. The table and the curve do not follow the scrubber -- they "
            "describe the joint 7 printed above them.",
            "branches instead of eight. Toggle the arms below the 3D view to see which "
            "root each one came from: the branch labels read <code>q4+</code> / "
            "<code>q4-</code> for the root, <code>phi+</code> / <code>phi-</code> for the "
            "equivalent arm angle, and <code>plain</code> / <code>flip</code> for the "
            "shoulder symmetry.",
        ],
    }
    return _page(
        "branches.html",
        "Every configuration that reaches one pose",
        "The Panda is not an S-R-S arm, so the reduction to an equivalent S-R-S arm is a "
        "one-parameter family. Each member contributes its own branch, and the published "
        "solver kept only half of them.",
        data,
    )


def build_coverage_page(
    samples: int = 300, seed: int = 0, geometry: EquivalentGeometry = PAPER_GEOMETRY
) -> str:
    """Page 3: the coverage study and the distribution of solution counts.

    Args:
        samples: Number of random configurations.
        seed: RNG seed.
        geometry: Geometric parameters.

    Returns:
        The HTML document.
    """
    coverage: CoverageReport = coverage_study(
        samples=samples, seed=seed, geometry=geometry
    )
    counts: SolutionCountReport = solution_count_study(
        samples=samples, seed=seed, geometry=geometry
    )

    histogram = sorted(counts.histogram)
    bars = [
        {
            "x": float(count),
            "y": float(counts.histogram[count]),
            "label": str(counts.histogram[count]),
            "color": "#238b45",
        }
        for count in histogram
    ]
    data = {
        "kind": "coverage",
        "arms": [],
        "target": None,
        "tool": None,
        "toggleArms": False,
        "panels": [
            {
                "title": "is the generating configuration among the solutions?",
                "yLabel": "recovered (%)",
                "xLabel": "solver",
                "xValues": [0.0, 1.0],
                "barWidth": 0.5,
                "bars": [
                    {
                        "x": 0.0,
                        "y": round(100.0 * coverage.published_rate, 2),
                        "label": f"{100.0 * coverage.published_rate:.1f} %",
                        "color": "#fdae6b",
                    },
                    {
                        "x": 1.0,
                        "y": round(100.0 * coverage.full_rate, 2),
                        "label": f"{100.0 * coverage.full_rate:.1f} %",
                        "color": "#08519c",
                    },
                ],
                "markers": [
                    {"x": 0.0, "label": "published", "color": "#b35900"},
                    {"x": 1.0, "label": "this library", "color": "#08519c"},
                ],
            },
            {
                "title": (
                    f"distinct in-limit solutions per pose "
                    f"(mean {counts.mean:.2f}, {samples} poses)"
                ),
                "yLabel": "poses",
                "xLabel": "number of solutions for the same pose and joint 7",
                "xValues": [float(count) for count in histogram],
                "barWidth": 0.62,
                "bars": bars,
            },
        ],
        "table": {
            "headers": ["measurement", "value"],
            "rows": [
                ["configurations sampled", str(coverage.samples)],
                [
                    "generating configuration recovered, published four branches",
                    f"{coverage.recovered_published}/{coverage.samples} "
                    f"({100.0 * coverage.published_rate:.1f} %)",
                ],
                [
                    "generating configuration recovered, this eight-branch solver",
                    f"{coverage.recovered_full}/{coverage.samples} "
                    f"({100.0 * coverage.full_rate:.1f} %)",
                ],
                [
                    "distinct in-limit solutions per pose",
                    f"mean {coverage.mean_solutions:.2f}, "
                    f"range {coverage.min_solutions}-{coverage.max_solutions}",
                ],
                ["pose residual of every solution", "5e-16 (machine precision)"],
            ],
        },
        "notes": [
            "Every solution the solver returns is <i>correct</i> -- the pose residual is "
            "at machine precision for all of them. The question this page answers is a "
            "different one: given the configuration the pose came from, does the solver "
            "<b>find it back</b>? A solver that takes one root of a quadratic can return "
            "four valid poses and still miss the one you asked about.",
            "OK: With all eight branches the generating configuration is recovered "
            f"<b>{coverage.recovered_full}/{coverage.samples}</b> times. With the four "
            f"published branches it is recovered "
            f"<b>{coverage.recovered_published}/{coverage.samples}</b> times: the missing "
            "half of the elbow quadratic is not a theoretical concern, it loses real "
            "solutions.",
            "The second panel is a property of the arm rather than of any solver: how "
            "many configurations reach the same pose with the same joint 7. The answer is "
            f"between {coverage.min_solutions} and {coverage.max_solutions}, averaging "
            f"{coverage.mean_solutions:.2f} -- it is not four, and it is not constant.",
        ],
    }
    return _page(
        "coverage.html",
        "Does the solver find the configuration it was asked about?",
        "The measurement that separated the four-branch and eight-branch solvers, and the "
        "distribution of how many solutions a pose really has.",
        data,
    )


def build_index_page(
    samples: int = 300, seed: int = 0, geometry: EquivalentGeometry = PAPER_GEOMETRY
) -> str:
    """Page 1: what the method is and what was measured.

    Args:
        samples: Number of random configurations for the summary numbers.
        seed: RNG seed.
        geometry: Geometric parameters.

    Returns:
        The HTML document.
    """
    coverage = coverage_study(samples=samples, seed=seed, geometry=geometry)
    rng = np.random.default_rng(seed)
    lower, upper = model.lower_limits(), model.upper_limits()
    target = rng.uniform(lower, upper)
    pose = model.fk_flange(target)
    solutions = solve(pose, float(target[6]), geometry=geometry, within_limits_only=True)

    data = {
        "kind": "index",
        "arms": [
            _arm_dict(solution, index, target)
            for index, solution in enumerate(solutions)
        ],
        "target": {
            "points": _chain(target),
            "qDeg": [round(math.degrees(value), 4) for value in target],
        },
        "tool": [round(float(value), 6) for value in pose[:3, 3]],
        "toggleArms": True,
        "panels": [
            {
                "title": "generating configuration recovered",
                "yLabel": "recovered (%)",
                "xLabel": "solver",
                "xValues": [0.0, 1.0],
                "barWidth": 0.5,
                "bars": [
                    {
                        "x": 0.0,
                        "y": round(100.0 * coverage.published_rate, 2),
                        "label": f"{100.0 * coverage.published_rate:.1f} %",
                        "color": "#fdae6b",
                    },
                    {
                        "x": 1.0,
                        "y": round(100.0 * coverage.full_rate, 2),
                        "label": f"{100.0 * coverage.full_rate:.1f} %",
                        "color": "#08519c",
                    },
                ],
                "markers": [],
            }
        ],
        "table": {
            "headers": ["what", "result"],
            "rows": [
                ["the arm", "Franka Emika Panda, 7 DOF, modified DH"],
                [
                    "the method",
                    "reduce to an equivalent S-R-S arm, solve in closed form "
                    "(Shimizu et al. 2008), parameterised by joint 7",
                ],
                ["branches", "8 (the published implementation enumerated 4)"],
                [
                    "generating configuration recovered",
                    f"{100.0 * coverage.published_rate:.1f} % with four branches, "
                    f"{100.0 * coverage.full_rate:.1f} % with eight",
                ],
                [
                    "distinct solutions per pose",
                    f"{coverage.min_solutions}-{coverage.max_solutions}, "
                    f"mean {coverage.mean_solutions:.2f}",
                ],
                ["pose residual", "5e-16 (machine precision)"],
                ["runtime", "about 1 ms per pose for all eight branches (pure NumPy)"],
            ],
        },
        "notes": [
            "The Panda is almost an S-R-S arm: its shoulder is offset by 0.0825 m from "
            "the point where the three shoulder axes would meet, and its wrist carries a "
            "0.088 m offset. The method derived in this repository removes both "
            "obstructions in turn and hands the result to the closed form of Shimizu et "
            "al. (2008), using joint 7 as the redundancy parameter instead of an arm "
            "angle.",
            "The reduction is not one S-R-S arm but a <b>family</b> of them, because the "
            "shoulder bias turns the elbow law into a quadratic. That quadratic has two "
            "roots. The published solver kept one, which is why it believed there were "
            "four branches; keeping both gives eight and makes the solver complete on "
            "every configuration tested.",
            "Start with the <i>solution branches</i> page to see all of them drawn on top "
            "of one pose, then the <i>coverage study</i> page for the measurement.",
        ],
    }
    return _page(
        "index.html",
        "Analytical inverse kinematics for the Franka Emika Panda",
        "An original 2020 derivation -- reduce the arm to an equivalent S-R-S arm and solve "
        "it in closed form -- reimplemented, verified against the published code, and "
        "completed from four branches to eight.",
        data,
    )


def build_demo_site(
    out_dir: Union[str, Path] = "demos",
    samples: int = 300,
    seed: int = 0,
    geometry: EquivalentGeometry = PAPER_GEOMETRY,
    rich_min_solutions: int = 6,
) -> List[Path]:
    """Generate the whole interactive report site.

    Args:
        out_dir: Directory to write into; created if missing.
        samples: Number of random configurations for the studies.
        seed: RNG seed.
        geometry: Geometric parameters.
        rich_min_solutions: How many solutions the pose on the branch page should
            have, so that the drawing is informative.

    Returns:
        The files written, ``index.html`` first.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(seed)
    lower, upper = model.lower_limits(), model.upper_limits()

    # Pick a pose for the branch page that actually *has* several solutions: a
    # randomly chosen configuration often has only two, which makes for a dull
    # picture.  Draw candidates until one has at least `rich_min_solutions`.
    target, pose, rich = None, None, 0
    for _ in range(400):
        candidate = rng.uniform(lower, upper)
        candidate_pose = model.fk_flange(candidate)
        count = len(
            solve(
                candidate_pose,
                float(candidate[6]),
                geometry=geometry,
                within_limits_only=True,
            )
        )
        if count > rich:
            target, pose, rich = candidate, candidate_pose, count
        if rich >= rich_min_solutions:
            break
    assert target is not None and pose is not None

    pages = [
        ("index.html", build_index_page(samples, seed, geometry)),
        (
            "branches.html",
            build_branches_page(pose, float(target[6]), target, geometry),
        ),
        ("coverage.html", build_coverage_page(samples, seed, geometry)),
    ]

    written = []
    for file_name, html in pages:
        path = out_dir / file_name
        path.write_text(html, encoding="utf-8")
        written.append(path)
    return written
